want-reflections: true
shaders:
  default-sky-type: 1
  default-outdoor-ambient-color: [200, 202, 230, 245]
  default-indoor-ambient-color: [255, 255, 255, 190]
  default-sun-color: [216, 207, 194, 600]
  default-sun-angle: [145, -80, 0]
  default-fog-color: [200, 202, 230, 245]
  default-fog-density: 0.001
  default-interior-light-color: [255, 255, 255, 255]
  dd:
   sky-type: 2
   sun-color: [216, 207, 194, 500]
   outdoor-ambient-color: [200, 202, 230, 255]
   fog-color: [200, 202, 230, 255]
   fog-density: 0.003
  br:
   sky-type: 2
   outdoor-ambient-color: [200, 202, 255, 220]
   sun-color: [216, 207, 194, 230]
   fog-color: [200, 202, 255, 262]
   fog-density: 0.002
  mm:
   sky-type: 3
   outdoor-ambient-color: [255, 207, 194, 205]
   sun-color: [255, 173, 153, 650]
   sun-angle: [93, -45, 0]
   fog-color: [255, 207, 194, 205]
  dl:
   sky-type: 4
   outdoor-ambient-color: [82, 132, 190, 175]
   fog-color: [82, 132, 190, 175]
   sun-color: [0, 0, 0, 255]
