want-reflections: true
shaders:
  default-sky-type: 1
  default-outdoor-ambient-color: [200, 202, 230, 240]
  default-indoor-ambient-color: [128, 128, 128, 255]
  default-sun-color: [216, 207, 194, 400]
  default-sun-angle: [145, -80, 0]
  default-fog-color: [200, 202, 230, 240]
  default-fog-density: 0.001
  default-interior-light-color: [255, 255, 255, 500]
  dd:
   sky-type: 2
  br:
   sky-type: 2
  mm:
   sky-type: 3
   outdoor-ambient-color: [110, 180, 204, 175]
   sun-color: [255, 109, 86, 500]
   sun-angle: [93, -30, 0]
   fog-color: [255, 109, 86, 500]
  dl:
   sky-type: 4
   outdoor-ambient-color: [82, 132, 190, 200]
   sun-color: [224, 213, 208, 260]