want-reflections: true
shaders:
  default-sky-type: 1
  default-outdoor-ambient-color: [194, 236, 252]
  default-indoor-ambient-color: [179, 179, 179]
  default-sun-color: [243, 224, 158]
  default-sun-angle: [165, -83, 0]
  default-fog-color: [194, 236, 252]
  default-fog-density: 0.001
  default-interior-light-color: [159, 237, 215]
  dd:
   sky-type: 2
  br:
   sky-type: 2
  mm:
   sky-type: 3
   outdoor-ambient-color: [110, 180, 204]
   sun-color: [255, 109, 86]
   sun-angle: [93, -30, 0]
   fog-color: [255, 109, 86]
  dl:
   sky-type: 4
   outdoor-ambient-color: [82, 132, 190]
   sun-color: [224, 213, 208]