want-reflections: true
shaders:
  default-sky-type: 1
  default-outdoor-ambient-color: [200, 202, 230, 140]
  default-indoor-ambient-color: [255, 255, 255, 190]
  default-sun-color: [216, 207, 194, 450]
  default-sun-angle: [145, -80, 0]
  default-fog-color: [200, 202, 230, 140]
  default-fog-density: 0.001
  default-interior-light-color: [255, 255, 255, 255]
  tt:
   sun-color: [216, 207, 194, 450]
  dd:
   sky-type: 2
   sun-color: [216, 207, 194, 150]
   outdoor-ambient-color: [200, 202, 230, 100]
   fog-color: [200, 202, 230, 100]
   fog-density: 0.003
  br:
   sky-type: 2
   sun-color: [216, 207, 194, 450]
   outdoor-ambient-color: [200, 202, 255, 150]
   fog-color: [200, 202, 255, 150]
   fog-density: 0.002
  mm:
   sky-type: 3
   outdoor-ambient-color: [255, 207, 194, 119]
   sun-color: [255, 173, 153, 120]
   sun-angle: [93, -45, 0]
   fog-color: [255, 207, 194, 110]
  dl:
   sky-type: 4
   outdoor-ambient-color: [82, 132, 190, 100]
   sun-color: [0, 0, 0, 255]
